spring.application.name=cruddemo

### JDBC ##

spring.datasource.url=jdbc:postgresql://localhost:5432/employee
spring.datasource.username=postgres
spring.datasource.password=springboot

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/index.html
springdoc.swagger-ui.enabled=true

## securtity
spring.security.user.name=user
spring.security.user.password=user